# Generated by Django 5.1.2 on 2024-11-06 05:42

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('pan_number', models.CharField(blank=True, default='0000 0000', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Invalid PAN number format', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxpayer_status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=255, null=True)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BasicTaxDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('financial_year', models.CharField(max_length=9)),
                ('age', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_80C', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('section_80D', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('section_80G', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('section_80E', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('section_80TTA', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('standard_deduction_old', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('standard_deduction_new', models.DecimalField(decimal_places=2, default=75000, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='apptax.basictaxdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hra', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('special_allowance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('lta', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('other_allowance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('hra_exempted', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('lta_exempted', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('income_from_interest', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('rental_income', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('interest_on_home_loan_self_occupied', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('interest_on_home_loan_let_out', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('income_from_digital_assets', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('other_income', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_details', to='apptax.basictaxdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_income_old_regime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_income_new_regime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_old_regime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_new_regime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_calculation', to='apptax.basictaxdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PAN', 'PAN Card'), ('TAX', 'Tax Paid Slip'), ('SALARY', 'Salary Slip'), ('OTHER', 'Other Document')], max_length=20)),
                ('document_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='document')),
                ('verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'document_type')},
            },
        ),
    ]
