# Generated by Django 5.1.2 on 2024-11-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptax', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomedetails',
            name='exemptions',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
